# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcff781f933afc85660801fe4a2bf6b0ea1f50a9c548168714f9f8718f388a71bd160515d4ecf2a53787a9ff3756d9b49caea837d2f463846ba2f4435fb6768d

test:
  secret_key_base: 0881c488112e30c9724f148fad4cdfc82811325123eacd6cf5c36d63cfae7ab4b6ad6d9d5e9e06de3b747273941a3ed59bb92af0d5e350f08cc0c3dd2cf15b4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
